### ISSUE TITLE
API: Fix chalk error in typescript API boilerplate template

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo-cli#197]
**Describe the bug**
Importing and using chalk in the [typescript API boilerplate template](https://github.com/code-collabo/node-mongo-api-boilerplate-template-TS) gives the following error:

````
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/mac/dev/collabo/nmgo-ts-api/node_modules/chalk/source/index.js from /Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts not supported.
Instead change the require of index.js in /Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.nodeDevHook [as .js] (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts:17:33)
    at Module._compile (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/rs/dmjbq_c945l5ym6hx5sxyy5r0000gn/T/ts-node-dev-hook-3677414275108084.js:69:33)
    at require.extensions.<computed> (/private/var/folders/rs/dmjbq_c945l5ym6hx5sxyy5r0000gn/T/ts-node-dev-hook-3677414275108084.js:71:20)
    at Object.nodeDevHook [as .ts] (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/ts-node-dev/lib/wrap.js:104:1)
    at Module._compile (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/source-map-support/source-map-support.js:568:25)
[ERROR] 02:34:03 Error: require() of ES Module /Users/mac/dev/collabo/nmgo-ts-api/node_modules/chalk/source/index.js from /Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts not supported.
Instead change the require of index.js in /Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts to a dynamic import() which is available in all CommonJS modules.

````

**To Reproduce**
1. Import chalk at the top of server.ts file or server.atlas.ts file:
````
import chalk from 'chalk';
````
2. Replace the console.log message inside the try block with:
````
console.log(chalk.green(`\nServer running at ${process.env.API_HOST_URL}`));
````
3. Run the dev server as specified on the [readme](https://github.com/code-collabo/node-mongo-api-boilerplate-template-TS).

**Comment by Ifycode** [comment]
Someone is already fixing this!

**Comment by oyenuga17** [comment]
@Ifycode please assign me

**Comment by oyenuga17** [comment]
okay
